name: quiz_learning_app
description: Cross-platform Quiz Learning App with offline-first support.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  go_router: ^14.1.4
  get_it: ^7.7.0
  dio: ^5.7.0
  connectivity_plus: ^6.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  html_unescape: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/mock/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  build_runner: ^2.4.11
